### ISSUE TITLE
Decide how to initialise new maverick repo

### ISSUE THREAD

**Issue by fnoop** [goodrobots/migration#2]
- fork of old repo
 - import?
 - mass commit

Would prefer not to be a fork - should be a new start, but there are a LOT of commits and issues in the old repo that have been used to document that development of the project.

**Comment by cglusky** [comment]
you can transfer the repo.  but if we do that then we need to remove this maverick repo (or rename it).

https://help.github.com/articles/about-repository-transfers/

up to you @fnoop seems like there is some good info in the issue queue you may want to preserve?

**Comment by SamuelDudley** [comment]
https://github.com/ahadik/git_mover/blob/master/README.md
This tool looks like a possible option to keep the past issue, milestone
and label goodness while moving the repository. The difference with this
and the github option is that the old repo will continue to exist and the
redirects won't be in place.

**Comment by fnoop** [comment]
Oh cool, the transfer repo looks good.  Keeping all the commit and issue history would be a good thing I think.  I'll probably close out most of the open issues to give it a fresh start.  That OK with everyone?

**Comment by SamuelDudley** [comment]
All good with me! I can see the transfer worked :)

**Comment by fnoop** [comment]
Does that look OK?  The open issues are mostly quite useful so I left them in place for now.  I cleared out a bunch of old crap in the wiki.  We should use projects going forward, they look great for structuring goals and releases.

**Comment by SamuelDudley** [comment]
Looks good and sounds like a plan!

**Comment by fnoop** [comment]
Migrated!
