### ISSUE TITLE
Move gitter chat rooms?

### ISSUE THREAD

**Issue by fnoop** [goodrobots/migration#4]
Gitter chat rooms are currently:
 https://gitter.im/companioncomputers

Should this be changed to:
 https://gitter.im/goodrobots

?

**Comment by SamuelDudley** [comment]
Seems logical to move the chatroom

**Comment by cglusky** [comment]
agree

**Comment by fnoop** [comment]
New chat rooms created:
https://gitter.im/goodrobots/Lobby
https://gitter.im/goodrobots/maverick
https://gitter.im/goodrobots/admin

gitter links updated in Maverick readme and docs, and old gitter room headers.  Unfortunately the discuss.ardupilot.org stupid forum settings don't allow you to edit posts older than a month or so.  Have whinged (again), hopefully it will be fixed and links there can then be fixed.
